site_name: Lucy's Plugins
theme:
  name: null
  custom_dir: 'cinder'
  disable_nav_previous_next: true
nav:
  - LucyCommonLib: commonlib.md
  - ProNouns: pronouns.md
  - ProNouns-Discord: pronouns-discord.md
  - ProFiles: profiles.md
  - Support: "https://support.lucyy.me"
